# -*- coding: utf-8 -*-
import produtos
# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from produtos import Ui_MainWindow


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mercearia_do_Ziron(object):
    def setupUi(self, Mercearia_do_Ziron):
        Mercearia_do_Ziron.setObjectName("Mercearia_do_Ziron")
        Mercearia_do_Ziron.resize(350, 550)
        Mercearia_do_Ziron.setMinimumSize(QtCore.QSize(350, 550))
        Mercearia_do_Ziron.setMaximumSize(QtCore.QSize(350, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("venv/favicon_io/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mercearia_do_Ziron.setWindowIcon(icon)
        self.menu_principal = QtWidgets.QWidget(Mercearia_do_Ziron)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.menu_principal.setFont(font)
        self.menu_principal.setObjectName("menu_principal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_principal)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QFrame(self.menu_principal)
        self.main.setStyleSheet("background-color: rgb(42, 156, 255);")
        self.main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setLineWidth(0)
        self.main.setObjectName("main")
        self.button_vendas = QtWidgets.QPushButton(self.main)
        self.button_vendas.setGeometry(QtCore.QRect(100, 190, 161, 51))
        self.button_vendas.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_vendas.setStyleSheet("background-color: rgb(41, 99, 161);")
        self.button_vendas.setObjectName("button_vendas")
        self.button_estoque = QtWidgets.QPushButton(self.main)
        self.button_estoque.setGeometry(QtCore.QRect(100, 280, 161, 51))
        self.button_estoque.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_estoque.setStyleSheet("background-color: rgb(41, 99, 161);")
        self.button_estoque.setObjectName("button_estoque")
        self.button_exportar = QtWidgets.QPushButton(self.main)
        self.button_exportar.setGeometry(QtCore.QRect(100, 390, 161, 51))
        self.button_exportar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_exportar.setStyleSheet("background-color: rgb(41, 99, 161);")
        self.button_exportar.setObjectName("button_exportar")
        self.label = QtWidgets.QLabel(self.main)
        self.label.setGeometry(QtCore.QRect(60, 50, 221, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.main)
        Mercearia_do_Ziron.setCentralWidget(self.menu_principal)

        self.retranslateUi(Mercearia_do_Ziron)
        QtCore.QMetaObject.connectSlotsByName(Mercearia_do_Ziron)


        self.button_estoque.clicked.connect(self.chekFields)



    def retranslateUi(self, Mercearia_do_Ziron):
        _translate = QtCore.QCoreApplication.translate
        Mercearia_do_Ziron.setWindowTitle(_translate("Mercearia_do_Ziron", "Mercearia do Ziron"))
        self.button_vendas.setText(_translate("Mercearia_do_Ziron", "VENDAS"))
        self.button_estoque.setText(_translate("Mercearia_do_Ziron", "ESTOQUE"))
        self.button_exportar.setText(_translate("Mercearia_do_Ziron", "Exportar para excel"))
        self.label.setText(_translate("Mercearia_do_Ziron", "Mercearia Do Ziron"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mercearia_do_Ziron = QtWidgets.QMainWindow()
    ui = Ui_Mercearia_do_Ziron()
    ui.setupUi(Mercearia_do_Ziron)
    Mercearia_do_Ziron.show()
    sys.exit(app.exec_())
